[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "dist"
  exclude = [
    './dist/cookie-policy/index.html',
    './dist/contattami/index.html', 
    './dist/link/index.html',
    './dist/tabella/index.html',
    './dist/migliori-universita-medicina/index.html',
    './dist/corsi-di-laurea-online/index.html'
  ]

[[redirects]]
  from = "/corsi-di-laurea-magistrale-a-ciclo-unico/"
  to = "/lauree-triennali-elenco/"
  status = 301
  force = true


[[redirects]]
  from = '/api/*'
  to = 'https://json-corsi-fastify.herokuapp.com/:splat'
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "credentialless"
    Cross-Origin-Opener-Policy = "same-origin"