[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "dist"
  exclude = [
    './dist/cookie-policy/index.html',
    './dist/contattami/index.html', 
    './dist/link/index.html',
    './dist/tabella/index.html'
  ]

[[redirects]]
  from = '/api/*'
  to = 'https://json-corsi-fastify.herokuapp.com/:splat'
  status = 200
  force = true
  headers = {X-From = "Netlify"}